# Generated by Django 4.2.3 on 2023-07-15 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('blog', '0007_alter_blogpage_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Blog category',
                'verbose_name_plural': 'Blog kategorys',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='blogpage',
            options={'verbose_name': 'Blog post', 'verbose_name_plural': 'Blog posts'},
        ),
    ]
