# Generated by Django 4.2.3 on 2023-07-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_categoryblogpage_alter_blogpage_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryBlogPage',
        ),
    ]
